### ISSUE TITLE
Can you share a copy of Versions: cross-code 0.3

### ISSUE THREAD

**Issue by 45498106** [2767mr/CCApiHelper#1]
Multiplayer by 2767Mr
Versions: 0.3
Description:

A simple multiplayer server for Cross-Code. WIP (not working jet) 

How to setup:
1.) Create folder named "public" in the same directory as "server.js"
2.) Copy runnable Game into the "public" folder
3.) Replace "public/js/game.compiled.js" with "game.compiled.js"(downlded)

How to start:
1.) Install node js on server
2.) Open cmd in the same folder as "server.js"
3.) Execute "node server.js"

How to play:
Connect to ip.ip.ip.ip:3000
(If you use the my method to start the game you have to connect to ip.ip.ip.ip:3000/en/start.html)

ps.I didn't find the 0.3 version of game.compiled.js.

Thank

**Comment by 2767mr** [comment]
This is a repository for CCApiHelper witch I given up on. The new projects I am working on are: CCLoader (A modloader) and CCMMO (A multiplayer-mod using CCLoader). I will publish these project in the near future. Thanks for your comment.
